### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by alwaystest** [googlesamples/android-LNotifications#1]
gradle shows 

```
No resource identifier found for attribute tabMode and tabGravity
```

need to add Design lib manually.

**Comment by mschoettle** [comment]
Yes, the following dependency needs to be added to the Application's build.gradle:

`compile "com.android.support:design:26.1.0"` (or whichever version is used for the other dependencies)

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
