### ISSUE TITLE
Please tell more exact steps to get this SW working ...

### ISSUE THREAD

**Issue by learner62** [googlesamples/android-LNotifications#2]
My Android Studio's version is 3.0.1 and if I just integrate from Github your project to Android Studio I have following errors that I would not like to see:

in android.support.design.widget.TabLayout attributes app:tabMode and tabGravity were not found. I commented them out and now there is an error package android.support.design.widget does not exist
etc.

and I'm sure if I solve this next problem arises and so on. From this description you see that I'm a newcomer in these technologies but I would like to get a working example first and then deepen my understanding of these technologies.

I just wanted to try how android notifications work on lock screen from implementation point of view but now I'm frustrated. What can I do; is there in Android Studio a magic button resolving all version conflicts etc. to get this work ? I would not like to study this long ...

Or is there some other github project demonstrating these things that works better.

**Comment by EzraLopez** [comment]
Were you eventually able to run it?

**Comment by learner62** [comment]
Unfortunatelly I had to stop this project because of lack of time and moved to other projects. I wish you good luck in your trials and maybe new versions of applied services help to solve this thing. I'm a novice in here and if I don't get tutorials running I'm in problems because of lack of knowledge ...

**Comment by EzraLopez** [comment]
Thanks @learner62! :) Wishing you all the best with your projects!
